version: '3.4'

services:
  skillsdb:
    container_name: skillsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  skillsearchapi:
    container_name: skillsearchapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://skillsdb:27017"
    depends_on:
      - skillsdb
    ports:
      - "8000:80"

  skilladdapi:
    container_name: skilladdapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://skillsdb:27017"
    depends_on:
      - skillsdb
    ports:
      - "8001:80"


  skillupdateapi:
    container_name: skillupdateapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://skillsdb:27017"
    depends_on:
      - skillsdb
    ports:
      - "8002:80"

